### PR TITLE
Fix some metric pages

### LINKED ISSUE #130: [Bug] Some Metric pages aren't accessible
Steps to reproduce:

- Checkout these link, when you have your local server running

[http://localhost:5000/#!/apps/reference-browser/metrics/experiments.metrics.active_experiment](http://localhost:5000/#!/apps/reference-browser/metrics/experiments.metrics.active_experiment)

 [http://localhost:5000/#!/apps/reference-browser/metrics/toolbar.events.url_committed](http://localhost:5000/#!/apps/reference-browser/metrics/toolbar.events.url_committed)

Here is the screenshot of the error it throws when accessed.

Screenshot 2020-10-19 at 9 40 09 AM

### PR DESCRIPTION
**Pull request by DawoodShahat**
This PR fixes #130

### CODE REVIEW

**Comment by mhmohona** [comment]
These are Bugzilla links. see?  https://bugzilla.mozilla.org/show_bug.cgi?id=1556751

**Comment by DawoodShahat** [comment]
Thanks @mhmohona I will update this in the next commit.

File: src/pages/MetricDetail.svelte [hunk 1]
```diff
@@ -72,9 +72,12 @@
...
         {#each metric.bugs as bug, i}
-          {#if bug.indexOf('http') > -1}
-            <a href={bug} title={bug} target="_blank"> {i + 1} </a>
-          {:else}<span>{bug}</span>{/if}
+          <a
+            href={typeof bug !== 'number' ? bug : `https://bugzilla.mozilla.org/show_bug.cgi?id=${bug}`}
+            title={bug}
+            target="_blank">
+            {i + 1}
+          </a>
```
Comment (wlach) [inline src/pages/MetricDetail.svelte:80]: While you're here, can you use the style @mhmohona used in #132? It's a little more descriptive to show the full URL.

(longer term we can come up with a better format for the bugs, but let's leave to later)

**Review by wlach — CHANGES_REQUESTED** [review]

**Review by wlach — APPROVED** [review]
