### PR TITLE
Use `_` instead of `-` to identify metric names (fixes #313)

### LINKED ISSUE #313: Backlinks from BigQuery view -> Metric don't work
In the BigQuery view, we currently have a backlink to the metric that generated it.

image

But the link is often wrong. For example for:

https://glean-dictionary-dev.netlify.app/apps/firefox-android-release/tables/metrics?search=metrics.string_list.addons_enabled_addons

The link should be:

https://glean-dictionary-dev.netlify.app/apps/firefox-android-release/metrics/addons-enabled_addons

But actually is:

https://glean-dictionary-dev.netlify.app/apps/firefox-android-release/metrics/addons_enabled_addons

### PR DESCRIPTION
**Pull request by Fenn-CS**
Replaced `.`s in metric ulrs with `_`s as a way to establish consistency with the metric names in BigQuery definitions.

Fixes : #313

### CODE REVIEW

File: src/pages/MetricDetail.svelte [hunk 1]
```diff
@@ -10,7 +10,7 @@
   import { pageTitle } from "../state/stores";
 
   export let params;
-  let metricName = params.metric.replaceAll("-", ".");
+  let metricName = params.metric;
```
Comment (wlach) [inline src/pages/MetricDetail.svelte:13]: I think we should just take out this variable and replace it with "params.metric" everywhere. I think `metricName` falsely implies that this is the real name of the metric, rather than an identifier.

**Review by wlach — CHANGES_REQUESTED** [review]
There's a minor unit test failure (see the circle ci logs) and I have one minor requested change, other than that, looks great!

File: src/pages/MetricDetail.svelte (hunk 1 above)
Comment (Fenn-CS) [reply src/pages/MetricDetail.svelte:13]: Yep! Makes sense.

**Review by wlach — COMMENTED** [review]
👍
