### PR TITLE
Not Found component created to better handle cases when items do not exist (fixes #108)

### LINKED ISSUE #108: Better handle cases where application/pings/metrics/table do not exist
Currently we just silently fail if the user navigates to an entity that does not exist. e.g.: 

http://localhost:5000/#!/apps/burnham2
http://localhost:5000/#!/apps/fenix-nightly/pings/activation-doesnotexist

It would be better if we displayed some kind of friendly error page saying something like "Could not find application `burnham2`" or "Could not find ping `application-doesnotexist`". I don't expect this to happen frequently but this sort of thing can happen occasionally (e.g. if an application is added and then withdrawn)

To accomplish this task, you'll want to create a new Svelte component to cover this functionality and update each page to use/display it in the event that fetching information fails.

### PR DESCRIPTION
**Pull request by nonbinaryfrog**
I keep getting a ReferenceError so I assume I have not created the component correctly.

### CODE REVIEW

File: src/components/NotFoundPage.svelte [hunk 1]
```diff
@@ -0,0 +1,30 @@
...
+ let app = new App({
+    target: document.body,
+    props: {
+        app: AppDetail,
+        list: AppList,
+        ping: PingDetail,
+        metric: MetricDetail,
+        table: TableDetail,
+    }
+})
```
Comment (acmiyaguchi) [inline src/components/NotFoundPage.svelte:17]: We shouldn't be creating a new app instance in a component, which is generally reserved for `main.js`. This is probably why you're getting strange issues.

In the actual pages, I would expect to something like the following in the main code. Of course, this can be implemented in a number of ways with similar behavior.

```js
{#await some_promise}
    ....
{:then ...}
   ...
{:error error}
  <NotFoundPage name={....}
{/awai}
```

The component defined here is included when fetching the resource fails. I'd recommend taking a look at the svelte tutorial on building components with props: https://svelte.dev/tutorial/declaring-props

File: src/components/SchemaNode.svelte [hunk 2]
```diff
@@ -9,7 +9,9 @@
     <span
       class="text-gray-700">{parentFields.join('.')}{parentFields.length ? '.' : ''}</span><span>{node.name}</span>
   </p>
-  {#if node.description}
+ {#if node.description === 'The channel the application is being distributed on.'}
```
Comment (acmiyaguchi) [inline src/components/SchemaNode.svelte:12]: Is this change related to the issue?

Comment (nonbinaryfrog) [reply src/components/SchemaNode.svelte:12]: Sorry, no, that was for the initial test I needed to do before getting assigned a task.

File: src/components/SchemaNode.svelte [hunk 3]
```diff
@@ -9,7 +9,9 @@
     <span
       class="text-gray-700">{parentFields.join('.')}{parentFields.length ? '.' : ''}</span><span>{node.name}</span>
   </p>
-  {#if node.description}
+  {#if node.description === 'The channel the application is being distributed on.'}
+    <p class="text-red-600 text-xs ml-2">{node.description}</p>
+  {:else}
```
Comment (acmiyaguchi) [inline src/components/SchemaNode.svelte:14]: Please remove unrelated code changes.

File: src/components/NotFoundPage.svelte [hunk 4]
```diff
@@ -0,0 +1,14 @@
...
+  export let pageName;
+  export let itemType;
+</script>
+
+<style>
+  h2 {
+    color: darkgray;
+    font-style: italic;
+  }
+</style>
```
Comment (acmiyaguchi) [inline src/components/NotFoundPage.svelte:11]: Lets leave styling out for now.

File: src/pages/AppDetail.svelte [hunk 5]
```diff
@@ -9,9 +10,8 @@
     });
 </script>
 
-<h1>{params.app}</h1>
-
 {#if app}
+  <h1>{params.app}</h1>
```
Comment (acmiyaguchi) [inline src/pages/AppDetail.svelte:14]: I'm pretty sure this code is out of date. Could you rebase/pull changes from the most recent version of the `main` branch?

**Review by acmiyaguchi — CHANGES_REQUESTED** [review]
Please fix any merge conflicts by pulling in the most recent changes on `main` and any related linting errors caught by CI.

File: src/components/NotFoundPage.svelte [hunk 6]
```diff
@@ -0,0 +1,14 @@
+<script>
```
Comment (acmiyaguchi) [inline src/components/NotFoundPage.svelte:1]: I think the name of the component should be something like `NotFound`, instead of `NotFoundPage`, since it's part of a page and not the page itself.

**Comment by wlach** [comment]
@nonbinaryfrog let us know when you're ready for another review! it appears that CI is currently failing and there's a few conflicts to be resolved.

**Comment by nonbinaryfrog** [comment]
I've resolved the error with Cl, I'll work on updating the code now

File: src/components/SchemaNode.svelte [hunk 7]
```diff
@@ -11,6 +11,8 @@
   </p>
   {#if node.description}
     <p class="text-gray-600 text-xs ml-2">{node.description}</p>
+  {:else}
+    <p class="text-gray-600 text-xs ml-2">{node.description}</p>
```
Comment (acmiyaguchi) [inline src/components/SchemaNode.svelte:15]: There should be no changes in this file.

**Review by acmiyaguchi — CHANGES_REQUESTED** [review]
This generally looks good to me, aside from the SchemaNode changes.

**Comment by acmiyaguchi** [comment]
Can you also update the PR title and description so it fits with https://github.com/mozilla/glean-dictionary/blob/main/CONTRIBUTING.md?

File: src/pages/AppDetail.svelte [hunk 8]
```diff
@@ -81,4 +82,6 @@
       </li>
     {/each}
   </ul>
+{:else}
```
Comment (acmiyaguchi) [inline src/pages/AppDetail.svelte:85]: One other small comment in this file -- it looks like the title in this page is outside of the `if` statement, so if it fails there will be two `<h1>` tags. Can you pull it into the conditional so it's consistent?

**Review by acmiyaguchi — COMMENTED** [review]
FYI, if you mention the issue in a comment (e.g. #108), it makes it much easier to cross reference the PR with the original issue.

**Review by acmiyaguchi — APPROVED** [review]
r+
