### PR TITLE
Keep metrics list in a fixed height container (fixes #285)

### LINKED ISSUE #285: Metrics list should be fixed in height
Currently the metrics list jumps around a bunch as you paginate through results:

image

This is because the height is not fixed. We should probably make it a fixed-height container, like we do with the schema browser:

image
https://glean-dictionary-dev.netlify.app/apps/fenix/tables/activation

Same argument goes for the list of pings. @Iinh you mentioned you'd be interested in working on this?

### PR DESCRIPTION
**Pull request by Iinh**
Fixes #285.

### Pull Request checklist

- [x] The pull request has a descriptive title (and a reference to an issue it
      fixes, if applicable)
- [x] All tests and linter checks are passing
- [x] The pull request is free of merge conflicts

### CODE REVIEW

File: src/components/ItemList.svelte [hunk 1]
```diff
@@ -33,20 +33,29 @@
...
-    {#each filteredItems as item}
-      <li>
-        <a href={getItemURL(appName, itemType, item.name)}>{item.name}</a>
-        <i><Markdown text={item.description} /></i>
-      </li>
-    {:else}
-      <p>Your search didn't match any {itemType}.</p>
-    {/each}
-  </ul>
+  <div class="item-browser mx-auto my-4 p-2">
```
Comment (wlach) [inline src/components/ItemList.svelte:47]: I wonder if it's better to define these properties here or in the class itself? It makes some intuitive sense that we'd do padding inline (since they aren't really a property of the "component"). Probably not worth worrying about too much at this juncture in any case.

**Review by wlach — APPROVED** [review]
Looks great! Thanks @Iinh. I'll go ahead and merge
