### PR TITLE
Link back to metric and ping definitions in source control (fixes #223)

### LINKED ISSUE #223: Link back to metric and ping definitions in source control
It is sometimes handy to be able to go *back* to the original definitions in GitHub (or other source repositories) where glean metrics and pings are defined (e.g. to fix a typo or make an edit). 

I would propose adding a "Defined in" field inside the metrics and ping pages that linked back to the metric and ping files at the appropriate line number. For example, for [the usage ping for mozregression](https://glean-dictionary-dev.netlify.app/#!/apps/mozregression/pings/usage), we would link back to:

https://github.com/mozilla/mozregression/blob/master/mozregression/pings.yaml#L4

The link name would be the unique part of the page after `/master/` (`mozregression/pings.yaml`)

Solving this issue would involve several steps:

1. Update the [glean_parser](https://github.com/mozilla/glean_parser/) to gather this information (this article on getting line number information from yaml files may prove useful: https://stackoverflow.com/questions/13319067/parsing-yaml-return-with-line-number) 
2. Gather this newly exposed data using glean-parser inside [probe-scraper](https://github.com/mozilla/probe-scraper/) and expose it.
3. Update our [own metadata gathering script](https://github.com/mozilla/glean-dictionary/blob/main/scripts/build-glean-metadata.py) to make use of this information.
4. Finally (the easy part) expose this data in the glean dictionary UI.

### PR DESCRIPTION
**Pull request by Iinh**
After https://github.com/mozilla/probe-scraper/pull/271, we can now link metrics and pings back to their original definition in source control. 

### Pull Request checklist

- [x] The pull request has a descriptive title (and a reference to an issue it
      fixes, if applicable)
- [x] All tests and linter checks are passing
- [x] The pull request is free of merge conflicts

### CODE REVIEW

**Review by wlach — COMMENTED** [review]
This seems right to me, let's wait for the schema deploy to land and see how it works.

**Review by wlach — COMMENTED** [review]
Code looks good! Let's wait until we can test before landing.

**Comment by wlach** [comment]
> > Code looks good! Let's wait until we can test before landing.
> 
> Not sure what test you're referring to?

Don't we need the schema deploy to go through before we'll have the requisite information?

**Comment by Iinh** [comment]
Ah I see, sorry I should have updated you on this: we already have the source_url information available since last Friday 🎉

File: src/data/schemas.js [hunk 1]
```diff
@@ -35,9 +39,10 @@ export const APPLICATION_DEFINITION_SCHEMA = [
 export const METRIC_DEFINITION_SCHEMA = [
   {
     title: "Source",
-    id: "repo_url",
+    id: "source_url",
     type: "link",
     helpText: "Where the source definition of the metric may be found.",
```
Comment (wlach) [inline src/data/schemas.js:44]:
```suggestion
    helpText: "Where the source definition of the metric may be found (referencing the first commit).",
```

**Review by wlach — APPROVED** [review]
Oh great! Yes, I see this seems to be working! I have one minor suggestion but other than that please land at your convenience. :)

**Comment by Iinh** [comment]
This was the first issue that I took on when the internship started, and 3 PRs later I'm now finally able to finish it on my (almost) last day yayyy. Thank you @wlach for guiding me through this!
