### PR TITLE
Display notification emails on application pages (fixes #151)

### LINKED ISSUE #151: Display notification emails on application pages
We currently display email addresses on the ping page:

Screen Shot 2020-10-21 at 3 57 49 PM
http://localhost:5000/#!/apps/mozregression/pings/usage

The repository metadata also has this information, however, and it would be good to display it on the application page (http://localhost:5000/#!/apps/mozregression).

As part of this implementation, let's create a component for rendering this type of information (maybe `EmailAddresses`?) nicely and create a story for it. One nicety we could add would be creating a `mailto:` URL for the email address, to make it a little easier to send a mail to the relevant party.

### PR DESCRIPTION
**Pull request by Iinh**
This PR fixes #151.
### What I did:
- Create a separate EmailAddress component to be used in Application and Ping pages. 
- Put the loop logic in the component since emails are always returned in an array
- Add `mailto:` link 
- Create stories for EmailAddress

 #### Pull Request checklist

- [x] The pull request has a descriptive title (and a reference to an issue it
      fixes, if applicable)
- [x] All tests and linter checks are passing
- [x] The pull request is free of merge conflicts

### CODE REVIEW

File: src/components/EmailAddress.svelte [hunk 1]
```diff
@@ -0,0 +1,20 @@
...
+<style>
+  td {
+    @apply border;
+    @apply p-2;
+  }
+</style>
+
+<tr>
+  <td>Notification Email{emails.length > 1 ? 's' : ''}</td>
+  <td>
```
Comment (wlach) [inline src/components/EmailAddress.svelte:14]: I think we should not include the table elements here-- we should focus the component purely on displaying email addresses (we may want to use different elements to organize stuff in different places, but still use this component).

File: src/components/EmailAddress.svelte [hunk 2]
```diff
@@ -0,0 +1,20 @@
...
+    {#each emails as email}
+      <a href="mailto:{email}" target="_blank">{email}</a>
+      <br />
```
Comment (wlach) [inline src/components/EmailAddress.svelte:17]: Instead of using `<br/>` here (which is a bit hacky), I'd put them in a span where class="block" (see original code)

**Review by wlach — CHANGES_REQUESTED** [review]
Great stuff, a few comments. Sorry for the delay on this review.

**Review by wlach — CHANGES_REQUESTED** [review]
Good stuff! In addition to the item pointed in the review, I think we should call this component `EmailAddresses`

File: src/components/EmailAddresses.svelte [hunk 3]
```diff
@@ -0,0 +1,8 @@
+<script>
+  export let emails;
+</script>
+
+{#each emails as email}
+  <span class="block">
+    <a href="mailto:{email}" target="_blank">{email}</a></span>
```
Comment (wlach) [inline src/components/EmailAddresses.svelte:7]: Any reason this was set to target=blank_? I don't think it should be necessary (suspecting it got added by mistake see also discussion in #142)

```suggestion
    <a href="mailto:{email}">{email}</a></span>
```

**Review by wlach — CHANGES_REQUESTED** [review]
Just one last question

File: src/components/EmailAddresses.svelte (hunk 3 above)
Comment (Iinh) [reply src/components/EmailAddresses.svelte]: I thought it would be nice for the users to open their browser-based email app in a new tab without having to leave the current Glean page. However I read discussion #142, I understand the reasoning for keeping default behavior for links for now. Suggested change committed.

**Review by wlach — APPROVED** [review]
Great stuff, thank you!
