### PR TITLE
Bug 1887694 - Generate events_stream SQL for events

### LINKED ISSUE #2185: Change autogenerated SQL to use `events_stream` tables
Instead of using the raw events tables.

### PR DESCRIPTION
**Pull request by Dexterp37**
Fixes #2185 

### Pull Request checklist

- [ ] The pull request has a descriptive title (and a reference to an issue it
      fixes, if applicable)
- [ ] All tests and linter checks are passing
- [ ] The pull request is free of merge conflicts

### CODE REVIEW

File: src/pages/MetricDetail.svelte [hunk 1]
```diff
@@ -54,7 +54,11 @@
     additionalInfo
   ) {
     if (metricType === "event") {
-      return getGleanEventQuery(table, additionalInfo);
+      // Although events might come from other pings, we override that and
+      // generate SQL just for the `events_stream`. This changes
+      // `some_database.table` to `some_database.events_stream`.
```
Comment (Dexterp37) [inline src/pages/MetricDetail.svelte:59]: I'm not really sure if we want to retain the old SQL code generation. Does it make any sense? This is quite a hack @badboy

File: src/data/gleanSql.js [hunk 2]
```diff
@@ -15,25 +15,23 @@ LIMIT 10`;
 
 export const getGleanEventQuery = (table, additionalInfo) => `
   -- Auto-generated by the Glean Dictionary.
-  -- https://docs.telemetry.mozilla.org/cookbooks/accessing_glean_data.html#event-metrics \n
+  -- https://docs.telemetry.mozilla.org/cookbooks/accessing_glean_data.html#event-metrics
 
 WITH events AS (
   SELECT
     submission_timestamp,
```
[the remark this answers is not in the document]
Comment (badboy) [reply src/data/gleanSql.js:22]: Yes. Seems like the better idea.

File: src/pages/MetricDetail.svelte (hunk 1 above)
Comment (badboy) [reply src/pages/MetricDetail.svelte:59]: For events that are not in an events ping this will be incorrect with this change, because they don't end up in the stream just yet.

But otherwise it's fine; no point in keeping the legacy way around

**Review by badboy — APPROVED** [review]
small thing, we could fix that in a followup as well.

File: src/pages/MetricDetail.svelte (hunk 1 above)
Comment (Dexterp37) [reply src/pages/MetricDetail.svelte:59]: Ok, what about this? We retain the old query for non 'events' pings until this gets fixed.

**Review by badboy — APPROVED** [review]
