### PR TITLE
Make URLs work consistently (fixes #257)

### LINKED ISSUE #257: Opening links in new tabs leads to a 404
Steps to reproduce:
1. Start in an app, e.g. https://glean-dictionary-dev.netlify.app/#!/apps/firefox-ios-beta
2. Control+click any of the metrics on that page, and the new tab is a 404: https://glean-dictionary-dev.netlify.app/apps/firefox-ios-beta/metrics/app.opened_as_default_browser

Clicking on it in _not_ a new tab does not 404.

### PR DESCRIPTION
**Pull request by wlach**
* Move away from hashbang routing
* All links that result in a 404 route to index.html on netlify

### Pull Request checklist

- [x] The pull request has a descriptive title (and a reference to an issue it
      fixes, if applicable)
- [x] All tests and linter checks are passing
- [x] The pull request is free of merge conflicts

### CODE REVIEW

File: src/pages/AppDetail.svelte [hunk 1]
```diff
@@ -118,8 +119,7 @@
         <ul>
           {#each filteredMetrics as metric}
             <li>
-              <a
-                href={`/apps/${params.app}/metrics/${metric.name}`}>{metric.name}</a>
+              <a href={getMetricURL(app.name, metric.name)}>{metric.name}</a>
```
Comment (wlach) [inline src/pages/AppDetail.svelte:122]: We do this dance because resources with a period (".") in them are considered "files with extensions" by the software we're using for serving static content locally ([sirv](https://github.com/lukeed/sirv))

File: src/state/urls.js [hunk 2]
```diff
@@ -0,0 +1,6 @@
+export function getMetricURL(appName, metricName) {
+  // workaround servers that incorrectly interpret url resources with a "." in
+  // them as having an extension (this is common for metrics) -- the glean
+  // schema doesn't allow `-`'s in metrics, so this should be ok
+  return `/apps/${appName}/metrics/${metricName.replace(/-/g, "i")}`;
```
Comment (robhudson) [inline src/state/urls.js:5]: This is odd to me... you're replacing hyphens with the string `i`?

File: tests/state.urls.test.js [hunk 3]
```diff
@@ -0,0 +1,7 @@
+import { getMetricURL } from "../src/state/urls";
+
+describe("metric URL replacing", () => {
+  it("works as expected", () => {
+    expect(getMetricURL("foo", "bar.baz")).toEqual("/apps/foo/metrics/bar.baz");
+  });
+});
```
Comment (robhudson) [inline tests/state.urls.test.js:7]: A test with a hyphen would be good b/c of the `replace` in the function.

File: src/pages/AppDetail.svelte (hunk 1 above)
Comment (robhudson) [reply src/pages/AppDetail.svelte:122]: I'm not sure I follow this... the test example also has a period in it.

File: src/state/urls.js (hunk 2 above)
Comment (wlach) [reply src/state/urls.js]: I messed this up while adding a test. 🤦 Should be good now.

File: tests/state.urls.test.js (hunk 3 above)
Comment (wlach) [reply tests/state.urls.test.js:7]: Indeed, this test was miswritten! Fixed now

File: src/App.svelte [hunk 4]
```diff
@@ -29,7 +29,12 @@
         : []),
       ...(ping ? [{ url: `/apps/${app}/pings/${ping}/`, name: ping }] : []),
       ...(metric
-        ? [{ url: `/apps/${app}/metrics/${metric}/`, name: metric }]
+        ? [
+            {
+              url: `/apps/${app}/metrics/${metric}/`,
+              name: metric.replaceAll("-", "."),
```
[the remark this answers is not in the document]
Comment (wlach) [reply src/App.svelte:35]: The `name` portion is visually displayed in the breadcrumb, so we want to restore it back to its original state. I admit this dance is a little awkward, but can't think of a better way of doing it offhand.

**Review by robhudson — APPROVED** [review]
